apiVersion: apps/v1
kind: Deployment
metadata:
  name: forecast-deployment
  labels:
    {{- include "realtime-weather-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: forecast-service
spec:
  replicas: {{ .Values.forecastService.replicaCount }}
  selector:
    matchLabels:
      {{- include "realtime-weather-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: forecast-service
  template:
    metadata:
      labels:
        {{- include "realtime-weather-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: forecast-service
    spec:
      {{- if .Values.forecastService.nodeSelector.enabled }}
      nodeSelector: # Using nodeSelector directly as defined in values.yaml
        {{ .Values.forecastService.nodeSelector.key }}: {{ .Values.forecastService.nodeSelector.value | quote }}
      {{- end }}
      containers:
        - name: forecast-predictor
          image: "{{ .Values.image.repository }}/forecast-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KAFKA_BROKER_URL
              value: {{ .Values.forecastService.env.KAFKA_BROKER_URL | quote }} # Corrected source
            - name: PROCESSED_WEATHER_TOPIC
              value: processed-weather-data
            - name: PREDICTIONS_TOPIC
              value: weather-predictions
          resources:
            {{- toYaml .Values.forecastService.resources | nindent 12 }}
