{{- if .Values.frontendService.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  labels:
    {{- include "realtime-weather-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.frontendService.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  {{- if .Values.frontendService.ingress.className }}
  ingressClassName: {{ .Values.frontendService.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.frontendService.ingress.host }}
      http:
        paths:
          {{- range .Values.frontendService.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: frontend-service
                port:
                  number: {{ $.Values.frontendService.service.port }}
          {{- end }}
  {{- if .Values.frontendService.ingress.tls }}
  tls:
    {{- toYaml .Values.frontendService.ingress.tls | nindent 8 }}
  {{- end }}
{{- end }}