# kubernetes/realtime-weather-app/templates/owm-api-key-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.owmApiKey.name }}
  labels:
    {{- include "realtime-weather-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.owmApiKey.key }}: {{ .Values.secrets.owmApiKey.valueBase64 | default "" | quote }}