# kubernetes/realtime-weather-app/templates/owm-api-key-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.owmApiKeySecretName }}
  labels:
    {{- include "realtime-weather-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.owmApiKeySecretKey }}: {{ .Values.secrets.owmApiKeyBase64 | b64enc | quote }}