replicaCount: 1
image:
  repository: bitnami/kafka
  tag: 3.6.1-debian-11-r0
  pullPolicy: IfNotPresent
service:
  port: 9092
storage:
  size: 5Gi
  accessModes: [ReadWriteOnce]
  storageClassName: local-path # Corrected StorageClass name
resources:
  requests:
    memory: "512Mi"
    cpu: "300m"
  limits:
    memory: "1Gi"
    cpu: "700m"

zookeeper:
  connect: "realtime-weather-app-zookeeper:2181"
extraEnvVars:
    - name: KAFKA_CFG_LISTENERS
      value: "PLAINTEXT://:9092"
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: "PLAINTEXT://$(KAFKA_HOST):9092"
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: "PLAINTEXT:PLAINTEXT"
    - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
      value: "PLAINTEXT"
    - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
      value: "PLAINTEXT"
