
image:
  repository: ghcr.io/vishvesh11/realtime-weather-forecasting
  tag: latest
  pullPolicy: Always

github:
  username: vishvesh11
  repositoryName: realtime-weather-forecasting


imagePullSecrets:
  - name: ghcr-secret

# --- Secrets Configuration ---
secrets:
  owmApiKey:
    createSecret: false
    name: owm-api-key-secret
    key: OWM_API_KEY

  influxdb:
    createSecret: false
    existingSecretName: influxdb-secrets
    keys:
      url: INFLUXDB_URL
      token: INFLUXDB_TOKEN
      org: INFLUXDB_ORG
      bucket: INFLUXDB_BUCKET

# --- Zookeeper Subchart Configuration ---
zookeeper:
  enabled: true
  replicaCount: 1 # For simplicity, a single Zookeeper instance
  image:
    repository: bitnami/zookeeper
    tag: 3.8.0 # Use the specific version you prefer/used before
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"

# --- Kafka Configuration ---
kafka:
  enabled: true
  replicaCount: 1 # For simplicity, a single Kafka broker
  image:
    repository: bitnami/kafka
    tag: 3.6.1 # Use the specific version you prefer/used before
    pullPolicy: IfNotPresent
  service:
    port: 9092 # Internal ClusterIP port for Kafka
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"


# --- Producer Service ---
producerService:
  enabled: true
  replicaCount: 1
  env:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

# --- Data Processor Service ---
dataProcessorService:
  enabled: true
  replicaCount: 1
  env:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"

# --- Forecast Service (ML Predictor) ---
forecastService:
  enabled: true
  replicaCount: 1
  nodeSelector:
    enabled: true
    key: "kubernetes.io/hostname"
    value: "vishvesh-server-2"
  env:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# --- Dashboard Backend Service ---
dashboardBackendService:
  enabled: true
  replicaCount: 1
  service:
    port: 5000
    targetPort: 5000
    type: ClusterIP
  env:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"


frontendService:
  enabled: true
  replicaCount: 1
  service:
    port: 3000
    targetPort: 3000
    type: ClusterIP
  ingress:
    enabled: true
    className: traefik
    host: weather.vishvesh.me
    paths:
      - path: /
        pathType: Prefix
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod-cloudflare
    tls:
      - hosts:
          - weather.vishvesh.me
        secretName: weather-vishvesh-me-tls
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
