apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: client
    - protocol: TCP
      port: 2888
      targetPort: 2888
      name: follower
    - protocol: TCP
      port: 3888
      targetPort: 3888
      name: election
  type: ClusterIP
