apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zookeeper.fullname" . }}-data
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 8 }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClassName }}