name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/**'
      - 'services/**'
      - 'frontend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: deployment
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN for authentication

      - name: Get Repository Name
        id: repo_name
        run: echo "::set-output name=name::$(echo '${{ github.repository }}' | cut -d'/' -f2)"

      - name: Build and Push Producer Service
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/producer-service:latest ./services/producer-service
          docker push ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/producer-service:latest

      - name: Build and Push Data Processor
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/data-processor:latest ./services/data-processor
          docker push ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/data-processor:latest

      - name: Build and Push Forecast Service
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/forecast-service:latest ./services/forecast
          docker push ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/forecast-service:latest

      - name: Build and Push Dashboard Backend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/dashboard-backend:latest ./services/dashboard-backend
          docker push ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/dashboard-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/frontend:latest ./frontend
          docker push ghcr.io/${{ github.actor }}/${{ steps.repo_name.outputs.name }}/frontend:latest

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.8.1'


      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl cluster-info
          kubectl get nodes # Add this to verify node connection

      - name: Create OWM API Key Kubernetes Secret
        run: |
          kubectl create secret generic owm-api-key-secret \
            --from-literal=OWM_API_KEY=${{ secrets.OWM_API_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Update Helm Chart Dependencies
        run: helm dependency update kubernetes/realtime-weather-app

      - name: Upgrade/Install Helm Chart
        run: |

          helm upgrade --install realtime-weather-app kubernetes/realtime-weather-app \
            --values kubernetes/realtime-weather-app/values.yaml \
            --set github.username=${{ github.actor }} \
            --set github.repositoryName=${{ steps.repo_name.outputs.name }} \
            --set secrets.owmApiKeyBase64=$(echo -n "${{ secrets.OWM_API_KEY }}" | base64 -w 0) \
            ${INFLUXDB_SECRET_SET_ARGS} \
            --namespace default
